# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=256)),
                ('course_name', models.CharField(max_length=256, unique=True)),
                ('course_display_level_ru', models.CharField(max_length=256, unique=True)),
                ('course_display_level_en', models.CharField(max_length=256, unique=True)),
                ('course_display_topics_ru', models.CharField(max_length=256, unique=True)),
                ('course_display_topics_en', models.CharField(max_length=256, unique=True)),
                ('course_description_ru', models.TextField()),
                ('course_description_en', models.TextField()),
                ('course_url', models.TextField()),
            ],
        ),
    ]
