# Generated by Django 2.0.6 on 2018-07-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='courses.Course')),
                ('course_display_name_ru', models.CharField(max_length=256, unique=True)),
                ('course_display_name_en', models.CharField(max_length=256, unique=True)),
                ('course_description', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
    ]
