# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_name',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_url',
            field=models.CharField(max_length=256),
        ),
    ]
