# Generated by Django 2.0.6 on 2018-07-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180708_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedescription',
            name='course_page_url',
            field=models.TextField(default=None, unique=True),
        ),
    ]
