# Generated by Django 2.0.6 on 2018-07-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursedescription_course_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedescription',
            name='course_page_url',
            field=models.TextField(unique=True),
        ),
    ]
