# Generated by Django 2.0.6 on 2018-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180708_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedescription',
            name='course_page_url',
            field=models.TextField(),
        ),
    ]
