# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180708_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedescription',
            old_name='course_page_url',
            new_name='course_url',
        ),
    ]
